version: '3'
services:
  web:
    build: .
    ports:
     - '8000:8000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/home/desnos
  redis:
    image: 'redis:alpine'
    volumes:
      - redis_data:/data
volumes:  
  redis_data: